version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/lanchonetedarua
    volumes:
      - ./src/lanchonetedarua:/app
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonetedarua