version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - dev.env
    volumes:
      - ./src/lanchonetedarua:/app
    depends_on:
      - db
      - migration
    networks:
      - lanchonetedarua_network
  
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - dev.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - lanchonetedarua_network

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/lanchonetedarua:/app
    command: >
      sh -c "/tmp/wait_for_host.sh db 5432 && cd /app/adapters/database/migrations && alembic upgrade head"
    networks:
      - lanchonetedarua_network

networks:
  lanchonetedarua_network:
