version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/lanchonetedarua
    volumes:
      - ./src/lanchonetedarua:/app
    depends_on:
      - db
      - migration
  
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonetedarua

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/lanchonetedarua:/app
    command: > 
      sh -c "/tmp/wait_for_host.sh db 5432 && cd /app/adapters/database/migrations && alembic upgrade head"