apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:   
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:   
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-container
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.postgresqlUsername }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresqlPassword }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.postgresqlDatabase }}"
        - name: DATABASE_URI
          value: "postgresql://postgres:postgres@teste-postgresq.default.svc.cluster.local:5432/lanchonetedarua"