apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  my_secret: {{ .Values.secret.my_secret }}
  POSTGRES_USER: {{ .Values.secret.postgresqlUsername }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresqlPassword }}
  POSTGRES_DB: {{ .Values.secret.postgresqlDatabase }}
