apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresqlUsername }}
  POSTGRES_DB: {{ .Values.secret.postgresqlDatabase }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  postgres-password: {{ .Values.secret.postgresPassword }}
