apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.appName }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc }}
  DATABASE_URI: {{ .Values.secrets.DATABASE_URI | b64enc }}

