replicaCount: 2

name: lanchonete-de-rua

nameOverride: null
fullnameOverride: null

global:
  postgresql:
    auth:
      postgresPassword: "dblanchonetederuapass"
      database: "lanchonetedarua"

image:
  repository: "lucasnishimoto05/lanchonete-de-rua:1.0.0"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

secret:
  postgresqlUsername: "cG9zdGdyZXM="
  postgresqlDatabase: "bGFuY2hvbmV0ZWRhcnVh"
  postgresPassword: "ZGJsYW5jaG9uZXRlZGVydWFwYXNzCg=="
