replicaCount: 2

name: lanchonete-de-rua

image:
  repository: lanchonete-de-rua

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

secret:
  my_secret: "Zm9vYmFy" # Isso é "foobar" em base64
  postgresqlUsername: "cG9zdGdyZXMK"

postgresql:
  postgresqlUsername: ${{ secrets.postgresqlUsername }}
  postgresqlPassword: ${{ secrets.postgresqlPassword }}
  postgresqlDatabase: ${{ secrets.postgresqlDatabase }}
