version: '3.2'
services:
  postgres-srv:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2021!"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

       
volumes:
  postgres-data-volume:
    external: true